### ISSUE TITLE
v.type in makeParams returns nil

### ISSUE THREAD

**Issue by Delphilante** [GitSparTV/discordia-slash#2]
For some users, the v.type (subCommand) returns nil. 
`Uncaught Error: /home/santa/deps/discordia-slash/Application.lua:33: attempt to call a nil value`

**Comment by GitSparTV** [comment]
Hi, can you provide the code you are using so I can test it?

**Comment by Delphilante** [comment]
It happens to any code, even with your ban example command.

It is related to specific phones/applications (for example an user who has an Asus phone, it breaks on him every time). These applications somehow cannot fetch the params.

**Comment by GitSparTV** [comment]
Oh, hm, this sounds like discord issue

**Comment by GitSparTV** [comment]
put this on line 49
![image](https://user-images.githubusercontent.com/5685050/114774394-d16ab600-9d78-11eb-8363-4f872f281917.png)
