### ISSUE TITLE
Command with no parameters errors

### ISSUE THREAD

**Issue by checkraisefold** [GitSparTV/discordia-slash#5]
https://github.com/GitSparTV/discordia-slash/blob/bb362159a17244c67d91ca47ad09dfb6d73a52af/Application.lua#L49

data.options is optional according to the interaction data structure spec
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure

```
Uncaught Error: ...uff/ACCOUNT TRACKER/deps/discordia-slash/Application.lua:26: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...uff/ACCOUNT TRACKER/deps/discordia-slash/Application.lua:26: in function 'makeParams'
        ...uff/ACCOUNT TRACKER/deps/discordia-slash/Application.lua:48: in function <...uff/ACCOUNT TRACKER/deps/discordia-slash/Application.lua:42>
```

**Comment by checkraisefold** [comment]
this is because the package on lit is outdated

**Comment by GitSparTV** [comment]
Fuck lit

**Comment by Yaumama** [comment]
use the git repo
