### ISSUE TITLE
bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Dripku0** [GitSparTV/discordia-slash#6]
Uncaught Error: discordia-slash/Application.lua:115: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by GitSparTV** [comment]
Are you sure you are using GitHub version and not from lit?

**Comment by Dripku0** [comment]
lit

**Comment by Dripku0** [comment]
im new to github how do i get the github version?

**Comment by Dripku0** [comment]
> 

still doesnt work gives me the same error

**Comment by Ta-noshii** [comment]
Close issue? @epicGamer2000 I assume you've fixed this/moved on already?
