### ISSUE TITLE
Invalid interation application command 

### ISSUE THREAD

**Issue by GTNT-Github** [GitSparTV/discordia-slash#7]
```
local dis = require("discordia")
local slash = require("discordia-slash")
slash.constructor()
local client = dis.Client()
client:useSlashCommands()

client:on("slashCommandsReady", function()
	client:slashCommand({
		name = "test2",
		description = "description",
		options = {
			{
				name = "arg",
				description = "argdesc",
				type = slash.enums.optionType.string,
				required = true
			}
		},
		callback = function(ia, params, cmd)

		end
	})
end)
```

Ran this code (Basically straight from the readme docs) and got this error
![Screenshot 2022-01-17 184351](https://user-images.githubusercontent.com/46801452/149848313-f6576606-43ff-47e7-b05a-9d7a0d3a42dc.png)

Console
![Screenshot 2022-01-17 184345](https://user-images.githubusercontent.com/46801452/149848311-be453a5e-328c-45ce-b130-2f2923f361c5.png)

I'm new to Discordia and this addon so sorry If I'm being dumb

**Comment by GitSparTV** [comment]
Did you install discordia-slash from github or lit?
if lit: download from github

**Comment by GTNT-Github** [comment]
I installed w/ lit, How would I install w/ Github? I don't see anything on the readme (I'm dumb when it comes to GitHub)

**Comment by GTNT-Github** [comment]
Nevermind, got it working :)
