### ISSUE TITLE
User option fails if user not in server

### ISSUE THREAD

**Issue by checkraisefold** [GitSparTV/discordia-slash#8]
If you pass a user that's not in the server to a slash command with a user option, it will error. Seems to be because it checks resolved.members which is actually resolved.users when the user isn't in the server.
https://github.com/GitSparTV/discordia-slash/blob/master/libs/client/Client.lua#L171

**Comment by GitSparTV** [comment]
In what situations guild commands will fail on this?

**Comment by checkraisefold** [comment]
> In what situations guild commands will fail on this?

If you have a slash command with a user option, and you `<@id>` mention someone that's not in the guild, the command fails and discordia-slash throws an error from line 171.

**Comment by GitSparTV** [comment]
I see, make a PR, I no longer maintain this and don't have time

**Comment by Ta-noshii** [comment]
Close this issue? #11
